import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/navbar";
import Footer from "@/components/layouts/footer";
import Sidebar from "@/components/layouts/sidebar/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh] flex  w-full`}
      >
        <Sidebar />
        <main className="flex-1 h-[100vh] flex flex-col">
          <header>
            <Navbar />
          </header>
          <div className="flex-1 overflow-hidden">
            {children}
          </div>
          <footer className="w-full flex items-center justify-center py-4">
            <Footer />
          </footer>
        </main>

      </body>
    </html>
  );
}
